name: workflows

on:
  release:
    types:
      - created

jobs:
  pytorch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (Docker Hub)
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pytorch-jetson-nano:latest
          file: Dockerfile
      - name: Build and Push (GHCR)
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-args: --platform=linux/arm64,linux/amd64 
